#!/bin/bash

if [ "$UID" -ne 0 ]
then
    echo "Please execute this script as root (e.g. with sudo)! Install aborted."
    exit 1
fi

DIR="/opt/droppy"
FILES=("droppy.py" "droppy.desktop" "ss_monitor.sh")

if [ -d $DIR ]
then
    echo "${DIR} already exists, deleting contents."
    rm -rf ${DIR}
fi

mkdir $DIR
echo "Directory ${DIR} created."

echo "Copying files."
for a_file in ${FILES[*]}
do
    cp $a_file $DIR
done

echo "Setting permissions."
chmod 755 "${DIR}/droppy.py"
chmod 755 "${DIR}/droppy.desktop"

echo "Copying application shortcut."
if [ -e /usr/share/applications/droppy.desktop ]
then
    rm /usr/share/applications/droppy.desktop
fi

ln -s "${DIR}/droppy.desktop" /usr/share/applications

echo "Linking application binary."
if [ -e /usr/local/bin/droppy ]
then
    rm /usr/local/bin/droppy
fi

ln -s "${DIR}/droppy.py" /usr/local/bin
mv /usr/local/bin/droppy.py /usr/local/bin/droppy